# Generated by Django 3.2.5 on 2021-07-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('img', models.ImageField(upload_to='myimage')),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('categoryid', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=20)),
                ('uploaded', models.BooleanField()),
                ('slug', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('isdoctor', models.BooleanField()),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
            ],
        ),
    ]
