# Generated by Django 4.1.3 on 2022-11-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogg',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bdate', models.CharField(max_length=25)),
                ('authorname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=1500)),
            ],
        ),
    ]
